apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argotest.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "argotest.labels" . | nindent 4 }}
  {{- with .Values.rollout.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "argotest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argotest.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  strategy:
    canary:
      stableService: {{ include "argotest.fullname" . }}-stable
      canaryService: {{ include "argotest.fullname" . }}-canary
      trafficRouting:
        nginx:
          stableIngress: {{ include "argotest.fullname" . }}-ingress
      steps:
        {{- range .Values.rollout.strategy.canary.steps }}
        {{- if .setWeight }}
        - setWeight: {{ .setWeight }}
        {{- else if .pause }}
        - pause: {{ toYaml .pause | nindent 10 }}
        {{- else if .pauseDuration }}
        - pause:
            duration: {{ .pauseDuration }}
        {{- end }}
        {{- end }}
