apiVersion: v1
kind: Service
metadata:
  name: {{ include "argotest.fullname" . }}-stable
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "argotest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "argotest.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argotest.fullname" . }}-canary
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "argotest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "argotest.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
