apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argotest-ingress
  namespace: argotest
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argotest.xiaofengyu.com
      secretName: argotest-tls
  rules:
    - host: argotest.xiaofengyu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argotest-stable
                port:
                  number: 80
