apiVersion: v1
kind: Service
metadata:
  name: argotest-stable
  namespace: argotest
spec:
  selector:
    app: argotest
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argotest-canary
  namespace: argotest
spec:
  selector:
    app: argotest
  ports:
    - port: 80
      targetPort: 8080
